# Generated by Django 5.1.3 on 2024-12-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeelingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('feeling', models.CharField(choices=[('HAPPY', 'Happy'), ('SAD', 'Sad'), ('NEUTRAL', 'Neutral'), ('MAD', 'Mad'), ('OTHER', 'Other')], max_length=20)),
            ],
        ),
    ]
