# Generated by Django 5.1.3 on 2024-12-10 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0003_dailyjournal'),
    ]

    operations = [
        migrations.AddField(
            model_name='feelingreport',
            name='journal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productivity.dailyjournal'),
            preserve_default=False,
        ),
    ]
