"""
This type stub file was generated by pyright.
"""

def user_passes_test(test_func, login_url=..., redirect_field_name=...): # -> Callable[..., _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any | HttpResponseRedirect]]:
    """
    Decorator for views that checks that the user passes the given test,
    redirecting to the log-in page if necessary. The test should be a callable
    that takes the user object and returns True if the user passes.
    """
    ...

def login_required(function=..., redirect_field_name=..., login_url=...): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any | HttpResponseRedirect] | Callable[..., _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any | HttpResponseRedirect]]:
    """
    Decorator for views that checks that the user is logged in, redirecting
    to the log-in page if necessary.
    """
    ...

def permission_required(perm, login_url=..., raise_exception=...): # -> Callable[..., _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any | HttpResponseRedirect]]:
    """
    Decorator for views that checks whether a user has a particular permission
    enabled, redirecting to the log-in page if necessary.
    If the raise_exception parameter is given the PermissionDenied exception
    is raised.
    """
    ...

