"""
This type stub file was generated by pyright.
"""

from django.core import validators
from django.utils.deconstruct import deconstructible

@deconstructible
class ASCIIUsernameValidator(validators.RegexValidator):
    regex = ...
    message = ...
    flags = ...


@deconstructible
class UnicodeUsernameValidator(validators.RegexValidator):
    regex = ...
    message = ...
    flags = ...


