"""
This type stub file was generated by pyright.
"""

"""Functions for use in URLsconfs."""
def include(arg, namespace=...): # -> tuple[ModuleType | Any, Any | None, Any | None]:
    ...

path = ...
re_path = ...
