"""
This type stub file was generated by pyright.
"""

from django.utils import tree
from django.utils.functional import cached_property

"""
Code to manage the creation and SQL rendering of 'where' constraints.
"""
AND = ...
OR = ...
XOR = ...
class WhereNode(tree.Node):
    """
    An SQL WHERE clause.

    The class is tied to the Query class that created it (in order to create
    the correct SQL).

    A child is usually an expression producing boolean values. Most likely the
    expression is a Lookup instance.

    However, a child could also be any class with as_sql() and either
    relabeled_clone() method or relabel_aliases() and clone() methods and
    contains_aggregate attribute.
    """
    default = ...
    resolved = ...
    conditional = ...
    def split_having_qualify(self, negated=..., must_group_by=...): # -> tuple[Self, None, None] | tuple[None, Self, None] | tuple[None, None, Self] | tuple[Node | None, Node | None, Node | None]:
        """
        Return three possibly None nodes: one for those parts of self that
        should be included in the WHERE clause, one for those parts of self
        that must be included in the HAVING clause, and one for those parts
        that refer to window functions.
        """
        ...
    
    def as_sql(self, compiler, connection): # -> tuple[str | Any, list[Any]]:
        """
        Return the SQL version of the where clause and the value to be
        substituted in. Return '', [] if this node matches everything,
        None, [] if this node is empty, and raise EmptyResultSet if this
        node can't match anything.
        """
        ...
    
    def get_group_by_cols(self): # -> list[Any]:
        ...
    
    def get_source_expressions(self):
        ...
    
    def set_source_expressions(self, children): # -> None:
        ...
    
    def relabel_aliases(self, change_map): # -> None:
        """
        Relabel the alias values of any children. 'change_map' is a dictionary
        mapping old (current) alias values to the new values.
        """
        ...
    
    def clone(self): # -> Node:
        ...
    
    def relabeled_clone(self, change_map): # -> Node:
        ...
    
    def replace_expressions(self, replacements): # -> Node:
        ...
    
    def get_refs(self): # -> set[Any]:
        ...
    
    @cached_property
    def contains_aggregate(self): # -> bool:
        ...
    
    @cached_property
    def contains_over_clause(self): # -> bool:
        ...
    
    @property
    def is_summary(self): # -> bool:
        ...
    
    def resolve_expression(self, *args, **kwargs): # -> Node:
        ...
    
    @cached_property
    def output_field(self): # -> BooleanField:
        ...
    
    def select_format(self, compiler, sql, params): # -> tuple[str | Any, Any]:
        ...
    
    def get_db_converters(self, connection):
        ...
    
    def get_lookup(self, lookup):
        ...
    
    def leaves(self): # -> Generator[Any, Any, None]:
        ...
    


class NothingNode:
    """A node that matches nothing."""
    contains_aggregate = ...
    contains_over_clause = ...
    def as_sql(self, compiler=..., connection=...):
        ...
    


class ExtraWhere:
    contains_aggregate = ...
    contains_over_clause = ...
    def __init__(self, sqls, params) -> None:
        ...
    
    def as_sql(self, compiler=..., connection=...): # -> tuple[LiteralString, list[Never]]:
        ...
    


class SubqueryConstraint:
    contains_aggregate = ...
    contains_over_clause = ...
    def __init__(self, alias, columns, targets, query_object) -> None:
        ...
    
    def as_sql(self, compiler, connection):
        ...
    


