"""
This type stub file was generated by pyright.
"""

from django.db.models import lookups
from django.db.models.lookups import FieldGetDbPrepValueMixin, PostgresOperatorLookup, Transform
from . import Field
from .mixins import CheckFieldDefaultMixin

__all__ = ["JSONField"]
class JSONField(CheckFieldDefaultMixin, Field):
    empty_strings_allowed = ...
    description = ...
    default_error_messages = ...
    _default_hint = ...
    def __init__(self, verbose_name=..., name=..., encoder=..., decoder=..., **kwargs) -> None:
        ...
    
    def check(self, **kwargs):
        ...
    
    def deconstruct(self): # -> tuple[Any | None, str, list[Any], dict[Any, Any]]:
        ...
    
    def from_db_value(self, value, expression, connection): # -> Any | str:
        ...
    
    def get_internal_type(self): # -> Literal['JSONField']:
        ...
    
    def get_db_prep_value(self, value, connection, prepared=...): # -> Value:
        ...
    
    def get_db_prep_save(self, value, connection): # -> Value:
        ...
    
    def get_transform(self, name): # -> type[Transform] | KeyTransformFactory:
        ...
    
    def validate(self, value, model_instance): # -> None:
        ...
    
    def value_to_string(self, obj): # -> Any:
        ...
    
    def formfield(self, **kwargs): # -> CharField | TypedChoiceField:
        ...
    


def compile_json_path(key_transforms, include_root=...): # -> str:
    ...

class DataContains(FieldGetDbPrepValueMixin, PostgresOperatorLookup):
    lookup_name = ...
    postgres_operator = ...
    def as_sql(self, compiler, connection): # -> tuple[str, tuple[Any, ...]]:
        ...
    


class ContainedBy(FieldGetDbPrepValueMixin, PostgresOperatorLookup):
    lookup_name = ...
    postgres_operator = ...
    def as_sql(self, compiler, connection): # -> tuple[str, tuple[Any, ...]]:
        ...
    


class HasKeyLookup(PostgresOperatorLookup):
    logical_operator = ...
    def compile_json_path_final_key(self, key_transform): # -> str:
        ...
    
    def as_sql(self, compiler, connection, template=...): # -> tuple[Any, tuple[Any, ...]]:
        ...
    
    def as_mysql(self, compiler, connection): # -> tuple[Any, tuple[Any, ...]]:
        ...
    
    def as_oracle(self, compiler, connection): # -> tuple[Any, list[Any]]:
        ...
    
    def as_postgresql(self, compiler, connection): # -> tuple[str, tuple[Any, ...]]:
        ...
    
    def as_sqlite(self, compiler, connection): # -> tuple[Any, tuple[Any, ...]]:
        ...
    


class HasKey(HasKeyLookup):
    lookup_name = ...
    postgres_operator = ...
    prepare_rhs = ...


class HasKeys(HasKeyLookup):
    lookup_name = ...
    postgres_operator = ...
    logical_operator = ...
    def get_prep_lookup(self): # -> list[str]:
        ...
    


class HasAnyKeys(HasKeys):
    lookup_name = ...
    postgres_operator = ...
    logical_operator = ...


class HasKeyOrArrayIndex(HasKey):
    def compile_json_path_final_key(self, key_transform): # -> str:
        ...
    


class CaseInsensitiveMixin:
    """
    Mixin to allow case-insensitive comparison of JSON values on MySQL.
    MySQL handles strings used in JSON context using the utf8mb4_bin collation.
    Because utf8mb4_bin is a binary collation, comparison of JSON values is
    case-sensitive.
    """
    def process_lhs(self, compiler, connection): # -> tuple[Any, Any]:
        ...
    
    def process_rhs(self, compiler, connection): # -> tuple[Any, Any]:
        ...
    


class JSONExact(lookups.Exact):
    can_use_none_as_rhs = ...
    def process_rhs(self, compiler, connection): # -> tuple[Any | str, list[str] | Any | list[Any]]:
        ...
    


class JSONIContains(CaseInsensitiveMixin, lookups.IContains):
    ...


class KeyTransform(Transform):
    postgres_operator = ...
    postgres_nested_operator = ...
    def __init__(self, key_name, *args, **kwargs) -> None:
        ...
    
    def preprocess_lhs(self, compiler, connection): # -> tuple[Any, Any, list[str]]:
        ...
    
    def as_mysql(self, compiler, connection): # -> tuple[Any, tuple[*tuple[Any, ...], str]]:
        ...
    
    def as_oracle(self, compiler, connection): # -> tuple[str, tuple[Any, ...]]:
        ...
    
    def as_postgresql(self, compiler, connection): # -> tuple[str, tuple[*tuple[Any, ...], list[str]]] | tuple[str, tuple[*tuple[Any, ...], int | str]]:
        ...
    
    def as_sqlite(self, compiler, connection): # -> tuple[str, tuple[Any | str, ...]]:
        ...
    


class KeyTextTransform(KeyTransform):
    postgres_operator = ...
    postgres_nested_operator = ...
    output_field = ...
    def as_mysql(self, compiler, connection): # -> tuple[Any, tuple[*tuple[Any, ...], str]]:
        ...
    
    @classmethod
    def from_lookup(cls, lookup): # -> Self:
        ...
    


KT = ...
class KeyTransformTextLookupMixin:
    """
    Mixin for combining with a lookup expecting a text lhs from a JSONField
    key lookup. On PostgreSQL, make use of the ->> operator instead of casting
    key values to text and performing the lookup on the resulting
    representation.
    """
    def __init__(self, key_transform, *args, **kwargs) -> None:
        ...
    


class KeyTransformIsNull(lookups.IsNull):
    def as_oracle(self, compiler, connection): # -> tuple[Any, list[Any]] | tuple[LiteralString, tuple[Any, ...]]:
        ...
    
    def as_sqlite(self, compiler, connection): # -> tuple[Any, tuple[Any, ...]]:
        ...
    


class KeyTransformIn(lookups.In):
    def resolve_expression_parameter(self, compiler, connection, sql, param): # -> tuple[LiteralString | Any | Literal['JSON_EXTRACT(%s, \'$\')'], Any | list[Any]]:
        ...
    


class KeyTransformExact(JSONExact):
    def process_rhs(self, compiler, connection): # -> tuple[Any, Any] | tuple[Literal['%s'], list[Any]] | tuple[Any | str, list[str] | Any | list[Any]]:
        ...
    
    def as_oracle(self, compiler, connection): # -> tuple[LiteralString, tuple[Any, ...]] | tuple[Any, list[Any]] | tuple[LiteralString, list[Any]]:
        ...
    


class KeyTransformIExact(CaseInsensitiveMixin, KeyTransformTextLookupMixin, lookups.IExact):
    ...


class KeyTransformIContains(CaseInsensitiveMixin, KeyTransformTextLookupMixin, lookups.IContains):
    ...


class KeyTransformStartsWith(KeyTransformTextLookupMixin, lookups.StartsWith):
    ...


class KeyTransformIStartsWith(CaseInsensitiveMixin, KeyTransformTextLookupMixin, lookups.IStartsWith):
    ...


class KeyTransformEndsWith(KeyTransformTextLookupMixin, lookups.EndsWith):
    ...


class KeyTransformIEndsWith(CaseInsensitiveMixin, KeyTransformTextLookupMixin, lookups.IEndsWith):
    ...


class KeyTransformRegex(KeyTransformTextLookupMixin, lookups.Regex):
    ...


class KeyTransformIRegex(CaseInsensitiveMixin, KeyTransformTextLookupMixin, lookups.IRegex):
    ...


class KeyTransformNumericLookupMixin:
    def process_rhs(self, compiler, connection): # -> tuple[Any, list[Any] | Any]:
        ...
    


class KeyTransformLt(KeyTransformNumericLookupMixin, lookups.LessThan):
    ...


class KeyTransformLte(KeyTransformNumericLookupMixin, lookups.LessThanOrEqual):
    ...


class KeyTransformGt(KeyTransformNumericLookupMixin, lookups.GreaterThan):
    ...


class KeyTransformGte(KeyTransformNumericLookupMixin, lookups.GreaterThanOrEqual):
    ...


class KeyTransformFactory:
    def __init__(self, key_name) -> None:
        ...
    
    def __call__(self, *args, **kwargs): # -> KeyTransform:
        ...
    


