"""
This type stub file was generated by pyright.
"""

import warnings
from django.conf import DEFAULT_STORAGE_ALIAS, settings
from django.utils.deprecation import RemovedInDjango51Warning
from django.utils.functional import LazyObject
from django.utils.module_loading import import_string
from .base import Storage
from .filesystem import FileSystemStorage
from .handler import InvalidStorageError, StorageHandler
from .memory import InMemoryStorage

__all__ = ("FileSystemStorage", "InMemoryStorage", "Storage", "DefaultStorage", "default_storage", "get_storage_class", "InvalidStorageError", "StorageHandler", "storages")
GET_STORAGE_CLASS_DEPRECATED_MSG = ...
def get_storage_class(import_path=...): # -> Any:
    ...

class DefaultStorage(LazyObject):
    ...


storages = ...
default_storage = ...
