"""
This type stub file was generated by pyright.
"""

from django.core.exceptions import ImproperlyConfigured
from django.utils.functional import cached_property

class InvalidStorageError(ImproperlyConfigured):
    ...


class StorageHandler:
    def __init__(self, backends=...) -> None:
        ...
    
    @cached_property
    def backends(self): # -> Any:
        ...
    
    def __getitem__(self, alias): # -> Any:
        ...
    
    def create_storage(self, params): # -> Any:
        ...
    


