"""
This type stub file was generated by pyright.
"""

UserModel = ...
def check_password(environ, username, password): # -> None:
    """
    Authenticate against Django's auth database.

    mod_wsgi docs specify None, True, False as return value depending
    on whether the user exists and authenticates.
    """
    ...

def groups_for_user(environ, username): # -> list[Any]:
    """
    Authorize a user based on groups
    """
    ...

