"""
This type stub file was generated by pyright.
"""

class MigrationExecutor:
    """
    End-to-end migration execution - load migrations and run them up or down
    to a specified set of targets.
    """
    def __init__(self, connection, progress_callback=...) -> None:
        ...
    
    def migration_plan(self, targets, clean_start=...): # -> list[Any]:
        """
        Given a set of targets, return a list of (Migration instance, backwards?).
        """
        ...
    
    def migrate(self, targets, plan=..., state=..., fake=..., fake_initial=...): # -> ProjectState:
        """
        Migrate the database up to the given targets.

        Django first needs to create all project states before a migration is
        (un)applied and in a second step run all the database operations.
        """
        ...
    
    def apply_migration(self, state, migration, fake=..., fake_initial=...): # -> ProjectState:
        """Run a migration forwards."""
        ...
    
    def record_migration(self, migration): # -> None:
        ...
    
    def unapply_migration(self, state, migration, fake=...):
        """Run a migration backwards."""
        ...
    
    def check_replacements(self): # -> None:
        """
        Mark replacement migrations applied if their replaced set all are.

        Do this unconditionally on every migrate, rather than just when
        migrations are applied or unapplied, to correctly handle the case
        when a new squash migration is pushed to a deployment that already had
        all its replaced migrations applied. In this case no new migration will
        be applied, but the applied state of the squashed migration must be
        maintained.
        """
        ...
    
    def detect_soft_applied(self, project_state, migration): # -> tuple[Literal[False], Any] | tuple[bool, ProjectState | Any]:
        """
        Test whether a migration has been implicitly applied - that the
        tables or columns it would create exist. This is intended only for use
        on initial migrations (as it only looks for CreateModel and AddField).
        """
        ...
    


