"""
This type stub file was generated by pyright.
"""

def async_unsafe(message): # -> _Wrapped[Callable[..., Any], object, Callable[..., Any], object] | Callable[..., _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]]:
    """
    Decorator to mark functions as async-unsafe. Someone trying to access
    the function while in an async context will get an error message.
    """
    ...

