"""
This type stub file was generated by pyright.
"""

def deconstructible(*args, path=...): # -> Callable[..., Any]:
    """
    Class decorator that allows the decorated class to be serialized
    by the migrations subsystem.

    The `path` kwarg specifies the import path.
    """
    ...

