"""
This type stub file was generated by pyright.
"""

def make_hashable(value): # -> tuple[tuple[Any, Any], ...] | tuple[Any, ...]:
    """
    Attempt to make value hashable or raise a TypeError if it fails.

    The returned value should generate the same hash for equal values.
    """
    ...

