"""
This type stub file was generated by pyright.
"""

class RequestSite:
    """
    A class that shares the primary interface of Site (i.e., it has ``domain``
    and ``name`` attributes) but gets its data from an HttpRequest object
    rather than from a database.

    The save() and delete() methods raise NotImplementedError.
    """
    def __init__(self, request) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def save(self, force_insert=..., force_update=...):
        ...
    
    def delete(self):
        ...
    


