"""
This type stub file was generated by pyright.
"""

def get_current_site(request): # -> Any | RequestSite:
    """
    Check if contrib.sites is installed and return either the current
    ``Site`` object or a ``RequestSite`` object based on the request.
    """
    ...

